### ISSUE TITLE
patch size not used

### ISSUE THREAD

**Issue by isega24** [lucidrains/segformer-pytorch#6]
Hi again,

I have also noticed that you don't use the parameter patch_size on [the construction function of the segformer.](https://github.com/lucidrains/segformer-pytorch/blob/5868d8e75b2360bf26a83bd03f2a8ec3d9b1e8f7/segformer_pytorch/segformer_pytorch.py#L156)

Is this okey?

**Comment by lucidrains** [comment]
@isega24 hey! yes you are right, i've removed it and decided to fix it to the overlapping patches of kernel size 7, stride 4, padding 3 as they did in the paper, for all versions of the segformer
